export let ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export let ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export let ALL_PRODUCTS_FAILURE = 'ALL_PRODUCTS_FAILURE';
export let SHOW_PRODUCT = 'SHOW_PRODUCT'
export let ADD_PRODUCT = 'ADD_PRODUCT';
export let REMOVE_PRODUCT = 'REMOVE_PRODUCT';